[package]
name = "telemetry_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"         
tokio = { version = "1.34.0", features = ["full"] } 
serde = { version = "1.0.188", features = ["derive"] } 
serde_json = "1.0.107"      
rand = "0.10.0-rc.5"             